name: flutter_landing_page
description: 'Static Landing Page built with Flutter.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.3.0

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  gap:
  get: ^4.6.6
  intersperse:
  provider:
  responsive_framework:
  riverpod_annotation:
  shadcn_ui:
  url_launcher:
  websafe_svg:
  youtube_player_iframe: ^4.0.4
  video_player: ^2.8.2
  chewie: ^1.7.4
  visibility_detector: ^0.4.0
  firebase_core:
  cloud_firestore:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/
