// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsViwsySEfmHMlrVJV1V87WQBaO3B3qQY',
    appId: '1:118927435111:web:b236522b1f1a1491fefbc2',
    messagingSenderId: '118927435111',
    projectId: 'etcweb-f5fba',
    authDomain: 'etcweb-f5fba.firebaseapp.com',
    storageBucket: 'etcweb-f5fba.firebasestorage.app',
    measurementId: 'G-SS8TRTXD27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA16mcP2gc0AITYouB9G2Oz5Cab3zz2fQA',
    appId: '1:118927435111:android:765c4473e4519c71fefbc2',
    messagingSenderId: '118927435111',
    projectId: 'etcweb-f5fba',
    storageBucket: 'etcweb-f5fba.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsViwsySEfmHMlrVJV1V87WQBaO3B3qQY',
    appId: '1:118927435111:web:c8653aa3225af37cfefbc2',
    messagingSenderId: '118927435111',
    projectId: 'etcweb-f5fba',
    authDomain: 'etcweb-f5fba.firebaseapp.com',
    storageBucket: 'etcweb-f5fba.firebasestorage.app',
    measurementId: 'G-CLH74FH6D3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfI_FwAbs9CNDLHrmtADWAdIvIVrj39Vw',
    appId: '1:118927435111:ios:b6821b7b972f334ffefbc2',
    messagingSenderId: '118927435111',
    projectId: 'etcweb-f5fba',
    storageBucket: 'etcweb-f5fba.firebasestorage.app',
    iosBundleId: 'com.htsuruo.flutterApp',
  );

}